
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 10086
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-customer/**
      serviceId: eureka-ribbon
    api-b:
      path: /api-admin/**
      serviceId: service-feign
